### ISSUE TITLE
Links containing accents are not matching the target note

### ISSUE THREAD

**Issue by danymat** [mickael-menu/zk#47]
Hello, I'm starting to use your scripts in order to filter my notes. 
I found that `zk list --orphan` does return a lot of notes for me. However I don't have this in neuron or obsidian.
Is it normal?

**Comment by mickael-menu** [comment]
Could you share an example of a note **A** that shouldn't be orphan? With:

* The path to **A**
* The path to a note **B** which links to note **A**
* The syntax of the link used to link to **A** in the content of **B**

**Comment by danymat** [comment]
Sure!: (all paths are from the same directory)

1. Path to note 202102251018: 

```
202102251018 La slip-box est un phénomène récent et ne peut pas être prouvé utile.md
```

2. Path to note 202102241246 which links to 202102251018:

```
202102241246 §1 Zettelkasten.md
```

3. The syntax of the link:

```
 ## Inquiétudes

 - [[202102251018 La slip-box est un phénomène récent et ne peut pas être prouvé utile]]
```

*Note: I'm on macOS 11.4, all notes are created in this computer*

**Comment by mickael-menu** [comment]
Looks like it's failing because of the accents. It could be an issue with the FS normalization, sometimes accents are not normalized to the same unicode characters between file paths and keyboard input.

Until this is fixed, you could also just use the ID prefix for your links. Not sure it works with Obsidian but this is a best practice to make sure you can retitle your notes without breaking your links.

```
 ## Inquiétudes

 - [[202102251018]]
```

You can either add the title after the link if you want some context, or use `zk`'s LSP server to automatically report the note title as a diagnostic: https://github.com/mickael-menu/zk/issues/22#issuecomment-841872435

<img width="600" alt="Screenshot 2021-05-16 at 21 44 05" src="https://user-images.githubusercontent.com/58686775/118411475-142fee80-b695-11eb-83e7-99b9e90942ac.png">

**Comment by danymat** [comment]
Thank you!

**Comment by mickael-menu** [comment]
@danymat This is fixed in https://github.com/mickael-menu/zk/pull/49, would you mind checking it before I merge the PR? Thanks.

You will need to run `zk index --force` with the updated `zk` to reindex the wiki links.

[zk-v0.5.0-1-g3dd4d3a-linux-amd64.tar.gz](https://github.com/mickael-menu/zk/files/6680764/zk-v0.5.0-1-g3dd4d3a-linux-amd64.tar.gz)
[zk-v0.5.0-1-g3dd4d3a-linux-arm64.tar.gz](https://github.com/mickael-menu/zk/files/6680766/zk-v0.5.0-1-g3dd4d3a-linux-arm64.tar.gz)
[zk-v0.5.0-1-g3dd4d3a-linux-i386.tar.gz](https://github.com/mickael-menu/zk/files/6680767/zk-v0.5.0-1-g3dd4d3a-linux-i386.tar.gz)
[zk-v0.5.0-1-g3dd4d3a-macos-x86_64.zip](https://github.com/mickael-menu/zk/files/6680770/zk-v0.5.0-1-g3dd4d3a-macos-x86_64.zip)

**Comment by danymat** [comment]
Hello @mickael-menu , I hope you're doing right
Thank's a lot for improving the application and caring about your users.
Unfortunately, I still have issues... I made my repo public if you want to test the notes in your machine : https://github.com/danymat/Brain

**Comment by mickael-menu** [comment]
@danymat I get only 9 orphan notes using `zk list --orphan` in your repo, after running `zk index --force` with the updated build. Did you try with one of the following prebuilt binaries? The fix is not yet in `develop`.

[zk-v0.5.0-1-g3dd4d3a-linux-amd64.tar.gz](https://github.com/mickael-menu/zk/files/6680764/zk-v0.5.0-1-g3dd4d3a-linux-amd64.tar.gz)
[zk-v0.5.0-1-g3dd4d3a-linux-arm64.tar.gz](https://github.com/mickael-menu/zk/files/6680766/zk-v0.5.0-1-g3dd4d3a-linux-arm64.tar.gz)
[zk-v0.5.0-1-g3dd4d3a-linux-i386.tar.gz](https://github.com/mickael-menu/zk/files/6680767/zk-v0.5.0-1-g3dd4d3a-linux-i386.tar.gz)
[zk-v0.5.0-1-g3dd4d3a-macos-x86_64.zip](https://github.com/mickael-menu/zk/files/6680770/zk-v0.5.0-1-g3dd4d3a-macos-x86_64.zip)

**Comment by danymat** [comment]
> @danymat I get only 9 orphan notes using `zk list --orphan` in your repo, after running `zk index --force` with the updated build. Did you try with one of the following prebuilt binaries? The fix is not yet in `develop`.
> 
> [zk-v0.5.0-1-g3dd4d3a-linux-amd64.tar.gz](https://github.com/mickael-menu/zk/files/6680764/zk-v0.5.0-1-g3dd4d3a-linux-amd64.tar.gz)
> [zk-v0.5.0-1-g3dd4d3a-linux-arm64.tar.gz](https://github.com/mickael-menu/zk/files/6680766/zk-v0.5.0-1-g3dd4d3a-linux-arm64.tar.gz)
> [zk-v0.5.0-1-g3dd4d3a-linux-i386.tar.gz](https://github.com/mickael-menu/zk/files/6680767/zk-v0.5.0-1-g3dd4d3a-linux-i386.tar.gz)
> [zk-v0.5.0-1-g3dd4d3a-macos-x86_64.zip](https://github.com/mickael-menu/zk/files/6680770/zk-v0.5.0-1-g3dd4d3a-macos-x86_64.zip)

I tried by compiling zk in the opened branch (because running the pre-compiled version for macOS  you specified returns me an error with icu4c, as latest version for icu4c in brew is 69.1)

**Comment by mickael-menu** [comment]
I'm not sure what's wrong then. Can you confirm you ran `zk index --force` with the new build? I'll assume the fix is correct since I could test it on your repo and will merge it. We'll see in the next release if that helps you out.

> I tried by compiling zk in the opened branch (because running the pre-compiled version for macOS you specified returns me an error with icu4c, as latest version for icu4c in brew is 69.1)

Ha interesting, I didn't know that could be an issue. I'll make sure to upgrade my icu4c for the next one, and will check if I can package the lib directly in `zk` somehow. Thanks for the feedback.

**Comment by danymat** [comment]
> I'm not sure what's wrong then. Can you confirm you ran `zk index --force` with the new build? I'll assume the fix is correct since I could test it on your repo and will merge it. We'll see in the next release if that helps you out.

When doing `zk --version` I get: `zk 0.5.0-5-g0c3b965`
I did git checkout `fix/wikilinks` and `./go build`, and replaced my previous compiled version with this new one.

**Comment by mickael-menu** [comment]
What you did looks correct to me.

I merged the PR in `main` and built a new version after upgrading my icu4c: 
[zk-v0.5.0-4-g5b877dd-macos-x86_64.zip](https://github.com/mickael-menu/zk/files/6704574/zk-v0.5.0-4-g5b877dd-macos-x86_64.zip)

You can check directly if the fix works by looking at the `links` table of the `.zk/notebook.db` SQLite database.

With the old build, the accents are messed up:
<img width="827" alt="Screenshot 2021-06-23 at 21 54 01" src="https://user-images.githubusercontent.com/58686775/123160386-66bbb200-d46e-11eb-90d3-261d32de307d.png">

After running `zk index --force`, I get:

<img width="944" alt="Screenshot 2021-06-23 at 21 55 04" src="https://user-images.githubusercontent.com/58686775/123160406-6f13ed00-d46e-11eb-9cc5-e40af5267ceb.png">

(Let me know if you want me to remove the screenshots)

**Comment by danymat** [comment]
Hello, sorry about the time off.
I did reindex the notes with the newest zk build:

<img width="787" alt="Capture d’écran 2021-07-02 à 12 34 12" src="https://user-images.githubusercontent.com/5306901/124262024-cf232700-db31-11eb-902b-d5ad32ab6219.png">

**Comment by mickael-menu** [comment]
Closing as it should be fixed in the latest 0.6.0 version.

**Comment by danymat** [comment]
Hello, it seems the problem is back again. What kind of information/logs do you need to better analyse the issue ?

**Comment by mickael-menu** [comment]
@danymat If you could come up with a `.tesh` file reproducing the issue that would help. Here's the one for this issue: https://github.com/mickael-menu/zk/blob/main/tests/issue-47.tesh

You can install [`tesh`](https://github.com/mickael-menu/tesh) if you want to try it, but it's not necessary. As you can see a `tesh` file is just a list of shell command and the expected output. The `cd issue-47` goes into this fixture folder: https://github.com/mickael-menu/zk/tree/main/tests/fixtures/issue-47

**Comment by danymat** [comment]
Ok so I think I have the culprit, and it seems to be macOS.
I still cannot know the root reason of it, but I tried running the `0.13` version on a Debian based machine on my personal wiki, without any worries. Running the same for my M1 silicon on Ventura 13.3.1 gives inconsistent and false returns.

Maybe this bit of information can help more in finding the root cause.
Do not hesitate to ask for more information, I will gladly respond to it

**Comment by mickael-menu** [comment]
Basically same as my previous message, if you can come up with `.tesh` file that exhibits the problem on macOS, that would be helpful.
